import { CropPreset } from './types';

export const SOCIAL_PRESETS: CropPreset[] = [
  {
    id: 'ig-post',
    name: 'Instagram Square',
    platform: 'Instagram',
    width: 1080,
    height: 1080,
    iconName: 'Instagram',
  },
  {
    id: 'ig-portrait',
    name: 'Instagram Portrait',
    platform: 'Instagram',
    width: 1080,
    height: 1350,
    iconName: 'Instagram',
  },
  {
    id: 'ig-story',
    name: 'Instagram Story / Reel',
    platform: 'Instagram',
    width: 1080,
    height: 1920,
    iconName: 'Smartphone',
    safeZoneType: 'instagram_story',
  },
  {
    id: 'tiktok',
    name: 'TikTok Video / Story',
    platform: 'TikTok',
    width: 1080,
    height: 1920,
    iconName: 'Video',
    safeZoneType: 'tiktok',
  },
  {
    id: 'yt-thumb',
    name: 'YouTube Thumbnail',
    platform: 'YouTube',
    width: 1280,
    height: 720,
    iconName: 'Youtube',
    safeZoneType: 'youtube_thumbnail',
  },
  {
    id: 'yt-banner',
    name: 'YouTube Banner',
    platform: 'YouTube',
    width: 2560,
    height: 1440,
    iconName: 'Youtube',
  },
  {
    id: 'x-post',
    name: 'X / Twitter Post',
    platform: 'X',
    width: 1200,
    height: 675,
    iconName: 'Twitter',
  },
  {
    id: 'x-header',
    name: 'X / Twitter Header',
    platform: 'X',
    width: 1500,
    height: 500,
    iconName: 'Twitter',
  },
  {
    id: 'li-post',
    name: 'LinkedIn Post',
    platform: 'LinkedIn',
    width: 1200,
    height: 627,
    iconName: 'Linkedin',
  },
  {
    id: 'li-banner',
    name: 'LinkedIn Banner',
    platform: 'LinkedIn',
    width: 1584,
    height: 396,
    iconName: 'Linkedin',
  },
  {
    id: 'fb-post',
    name: 'Facebook Post',
    platform: 'Facebook',
    width: 1200,
    height: 630,
    iconName: 'Facebook',
  },
  {
    id: 'fb-cover',
    name: 'Facebook Cover',
    platform: 'Facebook',
    width: 820,
    height: 312,
    iconName: 'Facebook',
  },
  {
    id: 'pin',
    name: 'Pinterest Pin',
    platform: 'Pinterest',
    width: 1000,
    height: 1500,
    iconName: 'Pin',
  },
];

